### ISSUE TITLE
Fine-tune pos tagging

### ISSUE THREAD

**Issue by BinhMinhs10** [VinAIResearch/PhoBERT#11]
Cho em hỏi là sau khi chuyển word thành subword, thì anh để nhãn các subword là gì ạ?  vd: (liên_cảng_A5, N) sau tách (liên_@@ cảng_@@ A5) .Ngoài ra em cũng muốn hỏi a có dùng thêm các kỹ thuật gì ko ạ, em định thử lại xem có kết qủa có đúng như trong bài báo ko thôi

**Comment by datquocnguyen** [comment]
<img width="630" alt="Screen Shot 2020-06-09 at 4 34 08 pm" src="https://user-images.githubusercontent.com/2412555/84131678-10e8b780-aa6f-11ea-9fb4-2f82f3fbce3a.png">
Also check the footnote 4.

**Comment by BinhMinhs10** [comment]
Vâng a, giờ khi evaluate em lại gặp vấn đề sau token câu có độ dài khác so với true_labels. vd: nhãn từ Nguyễn Đức Chung nhãn N nhưng khi predict thành Nguyễn Đức nhãn N và Chung là V. Thì anh đo accuracy như thế nào??

**Comment by datquocnguyen** [comment]
<img width="635" alt="Screen Shot 2020-06-12 at 6 04 41 pm" src="https://user-images.githubusercontent.com/2412555/84496530-4c85ba80-acd7-11ea-839e-2749fd756bf8.png">
Anh ko bị vấn đề như em
