### ISSUE TITLE
Missing `config.json` in `PhoBERT_large_fairseq`

### ISSUE THREAD

**Issue by hoangphucITJP** [VinAIResearch/PhoBERT#14]
First thing first, thank you for publishing the source code of PhoBERT.

The issue is just a minor one which is that I can't find the `config.json` file in `PhoBERT_large_fairseq` downloaded [here](https://github.com/VinAIResearch/PhoBERT#pre-trained-models-). Therefore I have to download the base pre-trained to grab the file.

Have a nice day!

**Comment by datquocnguyen** [comment]
We do not need `config.json` for the `fairseq` models. 
`config.json` is for the `transformers` models.
