### ISSUE TITLE
Question Answering for PhoBert.

### ISSUE THREAD

**Issue by vosybac** [VinAIResearch/PhoBERT#15]
I have run the question answering demo of djl library, https://djl.ai/, and it worked well for English.
I have found that VinAI has released PhoBERT, but I don't know how to use it in the djl library.
Can you help me?
Thanks in advance.

![DL4J-Bert](https://user-images.githubusercontent.com/639550/88634126-2e85e500-d0e0-11ea-8cae-cee6ec53bb10.png)

**Comment by datquocnguyen** [comment]
Close this issue because it does not report any bug w.r.t. PhoBERT!
