### ISSUE TITLE
Cách load trained model

### ISSUE THREAD

**Issue by 17521121** [VinAIResearch/PhoBERT#18]
Chào anh, lúc trước để load model đã train thì em load bằng 
self.roberta = RobertaModel(config)
thay vì
self.roberta = RobertaModel.from_pretrained("PhoBERT_base_transformers/model.bin", config=config)
(Em bọc trong class riêng )
Và model em save bằng torch.save (state_dict),
Vấn đề là em giờ k biết file config đó nằm đâu, hoặc có cách nào khác để load model đã train  , mong anh giải đáp

**Comment by datquocnguyen** [comment]
Hi, I have no idea to be able to answer your question :|
