### ISSUE TITLE
Cannot import name 'PhobertModel'

### ISSUE THREAD

**Issue by luantran1311** [VinAIResearch/PhoBERT#19]
I'm using Google Colab and cannot import the "PhoBERTModel" 
![image](https://user-images.githubusercontent.com/19511189/92609732-1ad5bd00-f2e1-11ea-8467-9fc08643aa3a.png)

**Comment by datquocnguyen** [comment]
Did you install transformers from our development branch?
    `git clone https://github.com/datquocnguyen/transformers.git`
    `cd transformers`
    `pip3 install .`

**Comment by luantran1311** [comment]
@datquocnguyen  Yes I have already done that but the issue is still there.

**Comment by datquocnguyen** [comment]
Please update the latest instruction: https://github.com/VinAIResearch/PhoBERT

**Comment by datquocnguyen** [comment]
And using AutoModel and AutoTokenizer/PhobertTokenizer =)
