### ISSUE TITLE
Named Entity Recognition by PhoBert

### ISSUE THREAD

**Issue by congdaoduy298** [VinAIResearch/PhoBERT#20]
Can I ask you about how to implement PhoBert to recognize named entity ? I am trying to do that but I don't know how. I need get results without having to train it. Is it impossible? Many thanks.

**Comment by chicuong209** [comment]
> Can I ask you about how to implement PhoBert to recognize named entity ? I am trying to do that but I don't know how. I need get results without having to train it. Is it impossible? Many thanks.

You definitely need to fine tune it in your data set. You can refer BertForTokenClassification from Huggingface to do this task.
