### ISSUE TITLE
when Phobert available on HuggingFace?

### ISSUE THREAD

**Issue by thanhphi0401** [VinAIResearch/PhoBERT#23]
Hi sir,
when Phobert available on HuggingFace?
I need it to use in Rasa NLU

**Comment by datquocnguyen** [comment]
It's already available. You should read the readme.md file.

**Comment by thanhphi0401** [comment]
But i don't see here https://huggingface.co/transformers/pretrained_models.html
How can i integrate with Rasa NLU sir?
Thank you
