### ISSUE TITLE
Error tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

### ISSUE THREAD

**Issue by trungtruc123** [VinAIResearch/PhoBERT#26]
I run pretrain PhoBERT error .
ValueError Traceback (most recent call last)
in ()
3
4 phobert = AutoModel.from_pretrained("vinai/phobert-base")
----> 5 tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")
6
7 # INPUT TEXT MUST BE ALREADY WORD-SEGMENTED!

/usr/local/lib/python3.6/dist-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
323 if tokenizer_class is None:
324 raise ValueError(
--> 325 "Tokenizer class {} does not exist or is not currently imported.".format(tokenizer_class_candidate)
326 )
327 return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)

ValueError: Tokenizer class PhobertTokenizerFast does not exist or is not currently imported.****

**Comment by datquocnguyen** [comment]
# For transformers v4.x+: 
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base", use_fast=False)

# For transformers v3.x: 
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

See readme.md for more details.

**Comment by trungtruc123** [comment]
thanks you bro.!

Vào Th 5, 10 thg 12, 2020 vào lúc 12:26 Dat Quoc Nguyen <
notifications@github.com> đã viết:
