### ISSUE TITLE
Xác nhận kết qủa POS tagging

### ISSUE THREAD

**Issue by BinhMinhs10** [VinAIResearch/PhoBERT#27]
- Em thử nghiệm kết quả fine-tune phobert trên vlsp2013 pos tag 
- Nhưng có vẻ data trong paper không giống data gốc như vlsp. Ví dụ như trong tập test vlsp có 2131 example trong khi paper chỉ có 2120 example
- anh có thể cho em xin data vlsp pos tag sau khi anh chỉnh sửa, để em có thể so sánh giữa các model chính xác nhất với ạ

**Comment by datquocnguyen** [comment]
Dữ liệu gốc vlsp 2013 test mình có từ 7 năm trước gồm 2120 câu. 
Bạn liên lạc vlsp để xin lại nhé.

**Comment by BinhMinhs10** [comment]
em lấy data vlsp pos tag thì có 2131 example test nên có thể a đã chỉnh sửa
data
,  anh có thể cho em xin data anh đã thử nghiệm được không ạ?
Em cám ơn ạ.


Vào Th 5, 17 thg 12, 2020 vào lúc 13:29 Dat Quoc Nguyen <
notifications@github.com> đã viết:

**Comment by datquocnguyen** [comment]
[VLSP2013_POS_test_POS_Column.txt](https://github.com/VinAIResearch/PhoBERT/files/5707513/VLSP2013_POS_test_POS_Column.txt)
Dữ liệu mình có là dữ liệu từ 7 năm trước khi tham gia vlsp 2013 gồm 2120 câu.
Hơn nhau 10 câu mình ko biết là nguyên nhân ở đâu, bạn cần kiểm tra lại nguồn dữ liệu của mình.
