### ISSUE TITLE
What is the max sequence length of the encoder and decoder?

### ISSUE THREAD

**Issue by ithieund** [VinAIResearch/PhoBERT#28]
Hi @datquocnguyen ,
Can you specify the max sequence length of the model's encoder and decoder?

I want you use this model for regression (text generation task). Is that possible?
Thank you very much!

**Comment by datquocnguyen** [comment]
Max sequence length is 256. Btw, it's a BERT-based model, i.e. Transformer encoder only.
It is possible to use PhoBERT for text generation: https://ai.stackexchange.com/questions/9141/can-bert-be-used-for-sentence-generating-tasks

**Comment by ithieund** [comment]
Thank you.
