### ISSUE TITLE
creating a pre-trained model

### ISSUE THREAD

**Issue by vr25** [VinAIResearch/PhoBERT#3]
Hi,

Thank you for releasing the language-specific model along with the instructions.

I want to create a similar language-specific pre-trained model. I was wondering if you could share the pre-training scripts and toy data (and maybe a short write-up) so that it is easier to pre-train similar BERT-based models in another language.

I just have one important question; how do you chunk the documents where the text is longer than 512 tokens. Also, do you just simply split at 512 tokens even if that sentence hasn't ended and consider another 512 tokens chunk beginning at the previous chunk end? Does this take a lot of memory?

Thanks!

**Comment by datquocnguyen** [comment]
Hi, we follow the tutorial here: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md

Each line in the pretraining dataset associates with a sentence. 
If a sentence is longer than the max sentence length, e.g. 256, then the sentence will be ignored during training. 

Cheers,
Dat.

**Comment by vr25** [comment]
Hi,

I followed the instructions at https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md

But I am running into this error:
![image](https://user-images.githubusercontent.com/22553367/77781306-b9b87680-702b-11ea-8de4-27f63c60b1ab.png)

I am using the wikitext-103-raw. Do you think it would be because of different PyTorch or TensorFlow versions?

I am using this configuration: 4x NVIDIA Tesla V100 GPUs with 16 GiB of memory.

Thanks, again!
