### ISSUE TITLE
post tagging?

### ISSUE THREAD

**Issue by sangohanfly** [VinAIResearch/PhoBERT#30]
Hi,

Could download the PhoBERT package with transformers; would you know then how to use post tagging afterwards?

Thanks!
Pierre

**Comment by datquocnguyen** [comment]
You can fine-tune PhoBERT for a sequence labeling task (https://github.com/huggingface/transformers/tree/master/examples/legacy/token-classification), using a Vietnamese POS tagging corpus (https://vlsp.org.vn/resources).
