### ISSUE TITLE
What's the meaning of position_ids = {0, 1}?

### ISSUE THREAD

**Issue by windysonic** [VinAIResearch/PhoBERT#35]
Hi, i notice that at [Line](https://github.com/huggingface/transformers/blob/ce111feed139d3e2a05bb364ad8ee186093ad3c7/src/transformers/models/roberta/modeling_roberta.py#L1558) here, the position id of the first input token will be 2. So what do the first two position ids stand for? And where are they used? Thanks for your patience and looking forward to your response!

**Comment by datquocnguyen** [comment]
https://github.com/facebookresearch/fairseq/issues/1187
