### ISSUE TITLE
Question about text lowercase and remove punctuation

### ISSUE THREAD

**Issue by jean2510** [VinAIResearch/PhoBERT#37]
Hi @datquocnguyen ,
I'm using PhoBERT for finding semantic textual similarity between sentences. I'm wonder is it necessary to perform lowercase and remove punctuation in the input text before feeding to model?
Thank you so much.

**Comment by datquocnguyen** [comment]
Hi, I think you can try both strategies, with vs. without lowercasing and punctuational removal, to see which one provides better performance.
