### ISSUE TITLE
support encode_batch for PhobertTokenizer?

### ISSUE THREAD

**Issue by hosjiu1702** [VinAIResearch/PhoBERT#39]
Could you support `encode_batch` method for a batch of inputs in the near future?

Thanks.

**Comment by datquocnguyen** [comment]
The process of merging a fast tokenizer for PhoBERT is in the discussion, as detailed in https://github.com/huggingface/transformers/pull/17254#issuecomment-1133932067. While waiting for this pull request's approval, if you would like to experiment with the fast tokenizer, you might install transformers as follows:
```
git clone --single-branch --branch fast_tokenizers_BARTpho_PhoBERT_BERTweet https://github.com/datquocnguyen/transformers.git
cd transformers
pip3 install -e .
```
