### ISSUE TITLE
Connection Error when loading rdrsegmenter

### ISSUE THREAD

**Issue by nguyentienviet123456** [VinAIResearch/PhoBERT#4]
Using this code 
```
from vncorenlp import VnCoreNLP
rdrsegmenter = VnCoreNLP("/Absolute-path-to/vncorenlp/VnCoreNLP-1.1.1.jar", annotators="wseg", max_heap_size='-Xmx500m') 
```
and get error

> ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=51159): Max retries exceeded with url: /annotators (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c11f250>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by datquocnguyen** [comment]
I haven't got this problem before. Are you deadling with a big file ? if yes, then please split it into smaller ones. 
It might be the case that the error comes from the `vncorenlp` python wrapper. You should put this issue to https://github.com/dnanhkhoa/python-vncorenlp
