### ISSUE TITLE
 word_ids() is not available when using Python-based tokenizers

### ISSUE THREAD

**Issue by Nguyendat-bit** [VinAIResearch/PhoBERT#40]
Hi, I'm getting this error now, is there any way to fix it 
![image](https://user-images.githubusercontent.com/34463182/159165819-da620e99-539b-4009-9ef4-edb623de08d1.png)

**Comment by datquocnguyen** [comment]
"tokenizers" likely makes use of a fast variant. And unfortunately, PhoBERTtokenizer currently does not support it atm. 
See: https://github.com/huggingface/transformers/pull/13788#pullrequestreview-771521131

**Comment by datquocnguyen** [comment]
@Nguyendat-bit 
The process of merging a fast tokenizer for PhoBERT is in the discussion, as detailed in https://github.com/huggingface/transformers/pull/17254#issuecomment-1133932067. While waiting for this pull request's approval, if you would like to experiment with the fast tokenizer, you might install transformers as follows:
```
git clone --single-branch --branch fast_tokenizers_BARTpho_PhoBERT_BERTweet https://github.com/datquocnguyen/transformers.git
cd transformers
pip3 install -e .
```

**Comment by Nguyendat-bit** [comment]
@datquocnguyen  Great, thank you so much
