### ISSUE TITLE
Can we use PhoBERT-base Tokenizer for PhoBERT-large model and vice versa?

### ISSUE THREAD

**Issue by ithieund** [VinAIResearch/PhoBERT#44]
Hi @datquocnguyen ,
Both PhoBERT-base Tokenizer and PhoBERT-large Tokenizer have the same vocab size = 64001. Then the question is can we use PhoBERT-base Tokenizer for PhoBERT-large model and vice versa? It means can we use only one of them to tokenize the dataset and use that prepared tokenized tensor dataset to do fine-tuning on downstream tasks for both PhoBERT-base Tokenizer and PhoBERT-large to save preparing time :)

**Comment by datquocnguyen** [comment]
Both pre-trained PhoBERT-base and PhoBERT-large models use the same tokenizer PhobertTokenizer.

**Comment by ithieund** [comment]
Thank you!
