### ISSUE TITLE
HFValidationError

### ISSUE THREAD

**Issue by lttkien1511** [VinAIResearch/PhoBERT#45]
Hi, when I run my training code, I get this error:
![validationerror](https://github.com/VinAIResearch/PhoBERT/assets/86515602/df41f9d3-d7e3-40ca-b96c-774c0ef455cd)
I ensure that I have pointed to the right path of the model in my server. Can you help me please?

**Comment by datquocnguyen** [comment]
`self.tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")` 
i.e. use "vinai/phobert-base" instead of "bert_weight/phobert-base/vocab.txt"
