### ISSUE TITLE
Wrong URL in the installation of VnCoreNLP's word segmenter

### ISSUE THREAD

**Issue by duydvu** [VinAIResearch/PhoBERT#5]
I followed the installation instructions in the "Using VnCoreNLP's word segmenter to pre-process input raw texts" section and then could not start the server.
It turned out that the `wordsegmenter.rdr` downloaded from the command
```
wget https://github.com/vncorenlp/VnCoreNLP/blob/master/models/wordsegmenter/wordsegmenter.rdr
``` 
is actually an HTML file.
So I replaced it by
```bash
wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/models/wordsegmenter/wordsegmenter.rdr
```
and it worked!

**Comment by datquocnguyen** [comment]
Thanks a lot! I will update the readme file =)
