### ISSUE TITLE
Thầy ơi, Cho mình hỏi thêm về PhoBert

### ISSUE THREAD

**Issue by xiketuan** [VinAIResearch/PhoBERT#7]
Mình đoc thấy Phobert dành cho chủ yếu: dich, thưc thể. Vì mình đang nghiên cứu về phân tích cảm xúc của xã hôi với cơ quan của mình, thì có thể dùng phobert thay thế đươc không a? Vì mới nghiên cứu chưa hiểu lắm nên hỏi thêm Thầy, Phobert này mình thay thế cho word2vec rồi dùng các mang neural như CNN, LSTM để phân loai ra Tích cưc , tiêu cưc, trung tính hay chỉ phobert là có thể phân loai ra đươc a?
Cảm ơn Thầy!

**Comment by datquocnguyen** [comment]
Yes. Please find an example at: https://github.com/suicao/PhoBert-Sentiment-Classification
Cheers,
Dat.
