### ISSUE TITLE
Can anyone pass the VLSP 2018 datasets application form to me?

### ISSUE THREAD

**Issue by cschou** [VinAIResearch/PhoBERT#8]
Hi,
I am working on a Vietnamese NER project and I need this dataset. However the official VLSP site seems to be down for days. Kindly share with me the application form and the e-mail address to send it to if possible. Sorry I don't know whom to ask (I am a newbie to Vietnamese NLP).

**Comment by datquocnguyen** [comment]
The VLSP website is up: https://vlsp.org.vn/resources

**Comment by datquocnguyen** [comment]
[VLSP2018-UserAgreement_0.pdf](https://github.com/VinAIResearch/PhoBERT/files/4556630/VLSP2018-UserAgreement_0.pdf)
