### ISSUE TITLE
Synergy Jina <> PhoBERT

### ISSUE THREAD

**Issue by hanxiao** [VinAIResearch/PhoBERT#9]
hi VinAI team,

Great work 👍 I'm the founder & CEO of Jina AI, you may have used/heard my prev. work on Fashion-MNIST and bert-as-service. I'm the creator of these two OSS.

I'm asking if we can build a synergy between Jina <> PhoBERT (& BERTwee, I post it separately). https://github.com/jina-ai/jina 
![image](https://github.com/jina-ai/jina/blob/master/.github/1500%D1%85667.gif?raw=true)

Simply put Jina is a universal neural search engine, it is a search infrastructure that can be used for searching text2text, image2image, audio2audio, etc. We already have [examples using Jina for QA and semantic text search here](https://github.com/jina-ai/examples/tree/master/southpark-search), full examples [can be found in here](https://github.com/jina-ai/examples).

## Potential synergy

1. I see great potential to apply this in production. Therefore I kindly ask if you are interested in port it into [jina](https://github.com/jina-ai/jina) or [jina-hub](https://github.com/jina-ai/jina-hub/). So that people can use it as one of their search component in Jina?

2. If you are interested in long-term collaboration, we also have a Slack channel, where we can invite you in to have more discussions. We also welcome your thoughts on it.

**Comment by datquocnguyen** [comment]
Hi, thanks for your interests. 
PhoBERT is released under the MIT license, thus you are free to port it into jina.
